#! /bin/sh
# /etc/init.d/temp_v2

### BEGIN INIT INFO
# Provides:          temp_v2.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start temp_v2.py on system boot
# Description:       This script will start / stop the oiltracker intelligent oil life monitoring service for temperature reading at system boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Intelligent Oil Life Monitor -- temp_v2 service"
    # run application you want to start
    /home/pi/development/release/temp_v2
    ;;
  stop)
    echo "Stopping Intelligent Oil Life Monitor -- temp_v2 service"
    # kill application you want to stop
    killall temp_v2
    ;;
  *)
    echo "Usage: /etc/init.d/temp_v2 {start|stop}"
    exit 1
    ;;
esac

exit 0
